/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import banco.CadastroContaDAO;
import classes.Cliente;
import java.time.ZoneId;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import prbancodigital.PrControleFinanceiro;

/**
 *
 * @author guilherme.miranda1
 */
public class FCadastroConta extends javax.swing.JFrame {

    Cliente cliente = new Cliente();
    private Date dataNC;

    /**
     * Creates new form FCadastroConta
     */
    public FCadastroConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtCNome = new javax.swing.JLabel();
        jCampoCNome = new javax.swing.JTextField();
        jTxtCFone = new javax.swing.JLabel();
        jTxtCDataNasc = new javax.swing.JLabel();
        jCampoCEmail = new javax.swing.JTextField();
        jTxtCEmail = new javax.swing.JLabel();
        jTxtCSexo = new javax.swing.JLabel();
        jBoxCSexo = new javax.swing.JComboBox<>();
        jCampoCDataNasc = new javax.swing.JFormattedTextField();
        jCampoCFone = new javax.swing.JFormattedTextField();
        jTxtCSenha = new javax.swing.JLabel();
        jCampoCSenha = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jTxtCUF = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCampoCidade = new javax.swing.JTextField();
        jCampoCRua = new javax.swing.JTextField();
        jTxtCRua = new javax.swing.JLabel();
        jTxtCCEP = new javax.swing.JLabel();
        jTxtCNum = new javax.swing.JLabel();
        jCampoCNum = new javax.swing.JTextField();
        jBoxCUF = new javax.swing.JComboBox<>();
        jCampoCCEP = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jCampoBairro = new javax.swing.JTextField();
        jTxtCCEP1 = new javax.swing.JLabel();
        jCampoPais = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jBotCCadastrar = new javax.swing.JButton();
        jCBotaoSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Cliente");
        setResizable(false);
        setSize(new java.awt.Dimension(390, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro Social"));

        jTxtCNome.setText("Nome:");

        jCampoCNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoCNomeActionPerformed(evt);
            }
        });

        jTxtCFone.setText("Telefone:");

        jTxtCDataNasc.setText("Data Nascimento:");

        jCampoCEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoCEmailActionPerformed(evt);
            }
        });

        jTxtCEmail.setText("E-mail:");

        jTxtCSexo.setText("Sexo:");

        jBoxCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", "Não Informar" }));
        jBoxCSexo.setSelectedIndex(2);
        jBoxCSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxCSexoActionPerformed(evt);
            }
        });

        try {
            jCampoCDataNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCampoCDataNasc.setToolTipText("");

        try {
            jCampoCFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTxtCSenha.setText("Senha:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtCEmail)
                        .addGap(25, 25, 25)
                        .addComponent(jCampoCEmail))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtCDataNasc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCampoCDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCSexo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTxtCFone)
                                .addGap(12, 12, 12)
                                .addComponent(jCampoCFone, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtCSenha)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCampoCSenha)
                            .addComponent(jBoxCSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTxtCNome)
                        .addGap(24, 24, 24)
                        .addComponent(jCampoCNome)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCNome)
                    .addComponent(jCampoCNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCFone)
                    .addComponent(jCampoCFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCSenha)
                    .addComponent(jCampoCSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCDataNasc)
                    .addComponent(jTxtCSexo)
                    .addComponent(jBoxCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCampoCDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoCEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCEmail))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCampoCNome.getAccessibleContext().setAccessibleName("jtxtCNome");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Endereço"));

        jTxtCUF.setText("Estado:");

        jLabel8.setText("Cidade:");

        jCampoCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoCidadeActionPerformed(evt);
            }
        });

        jCampoCRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoCRuaActionPerformed(evt);
            }
        });

        jTxtCRua.setText("Rua:");

        jTxtCCEP.setText("CEP:");

        jTxtCNum.setText("Nº:");

        jCampoCNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoCNumActionPerformed(evt);
            }
        });

        jBoxCUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "BA ", "CE ", "DE", "ES ", "GO ", "MA", "MT", "MS ", "MG ", "PA ", "PB ", "PR ", "PE ", "PI ", "RJ ", "RS ", "RO ", "SC ", "SP ", "SE ", "TO" }));
        jBoxCUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBoxCUFActionPerformed(evt);
            }
        });

        try {
            jCampoCCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Bairro:");

        jCampoBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoBairroActionPerformed(evt);
            }
        });

        jTxtCCEP1.setText("Pais:");

        jCampoPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoPaisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtCRua)
                            .addComponent(jTxtCCEP)
                            .addComponent(jTxtCCEP1))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCampoCRua, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jTxtCNum)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCampoCNum))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCampoPais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jCampoCCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTxtCUF)
                        .addGap(22, 22, 22)
                        .addComponent(jBoxCUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCampoCidade)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCUF)
                    .addComponent(jBoxCUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jCampoCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtCRua)
                    .addComponent(jCampoCRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCNum)
                    .addComponent(jCampoCNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCampoBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCCEP1)
                    .addComponent(jCampoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoCCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCCEP))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Cadastro de Cliente");

        jBotCCadastrar.setText("Cadastrar");
        jBotCCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotCCadastrarActionPerformed(evt);
            }
        });

        jCBotaoSair.setText("Sair");
        jCBotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBotaoSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jCBotaoSair)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBotCCadastrar)
                        .addGap(178, 178, 178))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBotCCadastrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jCBotaoSair)
                .addGap(15, 15, 15))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCampoCNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoCNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoCNomeActionPerformed

    private void jCampoCEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoCEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoCEmailActionPerformed

    private void jBoxCUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxCUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxCUFActionPerformed

    private void jCampoCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoCidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoCidadeActionPerformed

    private void jCampoCRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoCRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoCRuaActionPerformed

    private void jCampoCNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoCNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoCNumActionPerformed

    private void jBoxCSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBoxCSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBoxCSexoActionPerformed

    public Date ValidarData(Date dataNC) throws ParseException {
        SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        dataNC = sdf.parse(dataNC.toString());

        return dataNC;
    }

    private void jBotCCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotCCadastrarActionPerformed

        CadastroContaDAO ccDao = new CadastroContaDAO();
        String stringDate = jCampoCDataNasc.getText();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(stringDate, formatter);
        Date data = Date.from(date.atStartOfDay(ZoneId.systemDefault()).toInstant());

        // Salva as informações no Getters and Setters
        cliente.setNome(jCampoCNome.getText());
        cliente.setDataNasc(data); // retornando um valor null
        cliente.setSexo((String) jBoxCSexo.getSelectedItem());
        cliente.setEmail(jCampoCEmail.getText());
        cliente.setSenha(jCampoCSenha.getText());

        // Salva as informações de endereço no Getters and Setters
        cliente.getEndereco().setEstado((String) jBoxCUF.getSelectedItem());
        cliente.getEndereco().setCidade(jCampoCidade.getText());
        cliente.getEndereco().setRua(jCampoCRua.getText());
        cliente.getEndereco().setNumRua(jCampoCNum.getText());
        cliente.getEndereco().setCep(jCampoCCEP.getText());
        ccDao.InserirDadosBanco(cliente);

        String[] args = null;
        /**
         * @Dispose - Fecha as janelas atribuidas a aquela janela
         */

        PrControleFinanceiro.main(args);
        // FLogin ViewLogin = new FLogin();
        // ViewLogin.setVisible(true);

        dispose();

    }//GEN-LAST:event_jBotCCadastrarActionPerformed

    private void jCBotaoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBotaoSairActionPerformed
        String[] args = null;
        /**
         * @Dispose - Fecha as janelas atribuidas a aquela janela
         */
        this.dispose();
        PrControleFinanceiro.main(args);

    }//GEN-LAST:event_jCBotaoSairActionPerformed

    private void jCampoBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoBairroActionPerformed

    private void jCampoPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCampoPaisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FCadastroConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FCadastroConta().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBotCCadastrar;
    public javax.swing.JComboBox<String> jBoxCSexo;
    public javax.swing.JComboBox<String> jBoxCUF;
    private javax.swing.JButton jCBotaoSair;
    public javax.swing.JTextField jCampoBairro;
    private javax.swing.JFormattedTextField jCampoCCEP;
    public javax.swing.JFormattedTextField jCampoCDataNasc;
    public javax.swing.JTextField jCampoCEmail;
    private javax.swing.JFormattedTextField jCampoCFone;
    public javax.swing.JTextField jCampoCNome;
    public javax.swing.JTextField jCampoCNum;
    public javax.swing.JTextField jCampoCRua;
    public javax.swing.JPasswordField jCampoCSenha;
    public javax.swing.JTextField jCampoCidade;
    public javax.swing.JTextField jCampoPais;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jTxtCCEP;
    private javax.swing.JLabel jTxtCCEP1;
    private javax.swing.JLabel jTxtCDataNasc;
    private javax.swing.JLabel jTxtCEmail;
    private javax.swing.JLabel jTxtCFone;
    private javax.swing.JLabel jTxtCNome;
    private javax.swing.JLabel jTxtCNum;
    private javax.swing.JLabel jTxtCRua;
    private javax.swing.JLabel jTxtCSenha;
    private javax.swing.JLabel jTxtCSexo;
    private javax.swing.JLabel jTxtCUF;
    // End of variables declaration//GEN-END:variables

}
