/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author guilherme.miranda1
 */
public class FLogin extends javax.swing.JFrame {

    FPrincipal form_principal; 
    
    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotLEntrar = new javax.swing.JButton();
        jCampoLCPF = new javax.swing.JFormattedTextField();
        jTxtLCPF = new javax.swing.JLabel();
        jTxtLSenha = new javax.swing.JLabel();
        jCampoLSenha = new javax.swing.JPasswordField();
        jBotLCConta = new javax.swing.JButton();
        jTxtLLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(390, 600));

        jBotLEntrar.setText("Entrar");
        jBotLEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBotLEntrarMouseClicked(evt);
            }
        });
        jBotLEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotLEntrarActionPerformed(evt);
            }
        });

        try {
            jCampoLCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jCampoLCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoLCPFActionPerformed(evt);
            }
        });

        jTxtLCPF.setText("CPF:");

        jTxtLSenha.setText("Senha:");

        jCampoLSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCampoLSenhaActionPerformed(evt);
            }
        });

        jBotLCConta.setText("Criar conta");
        jBotLCConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotLCContaActionPerformed(evt);
            }
        });

        jTxtLLogo.setFont(new java.awt.Font("Vladimir Script", 0, 48)); // NOI18N
        jTxtLLogo.setText("Atlantis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtLCPF)
                            .addComponent(jTxtLSenha))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCampoLCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                            .addComponent(jCampoLSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBotLCConta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBotLEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jTxtLLogo)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jTxtLLogo)
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoLCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLCPF))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCampoLSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLSenha))
                .addGap(62, 62, 62)
                .addComponent(jBotLEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jBotLCConta)
                .addGap(145, 145, 145))
        );

        jCampoLCPF.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotLEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotLEntrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBotLEntrarActionPerformed

    private void jCampoLCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoLCPFActionPerformed
        
    }//GEN-LAST:event_jCampoLCPFActionPerformed

    private void jCampoLSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCampoLSenhaActionPerformed
        
    }//GEN-LAST:event_jCampoLSenhaActionPerformed

    private void jBotLCContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotLCContaActionPerformed
        // Associação a view de Cadastrar Conta 
       
        FCadastroConta ViewCadConta = new FCadastroConta();
        ViewCadConta.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBotLCContaActionPerformed

    private void jBotLEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBotLEntrarMouseClicked
        // Criar mecanismo de verificação de senha
                           
    }//GEN-LAST:event_jBotLEntrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBotLCConta;
    public javax.swing.JButton jBotLEntrar;
    public javax.swing.JFormattedTextField jCampoLCPF;
    public javax.swing.JPasswordField jCampoLSenha;
    private javax.swing.JLabel jTxtLCPF;
    private javax.swing.JLabel jTxtLLogo;
    private javax.swing.JLabel jTxtLSenha;
    // End of variables declaration//GEN-END:variables
}
